nodeLinker: node-modules

packageExtensions: {
  "@parcel/node-resolver-core@^3.6.2": {
      dependencies: {
        "@parcel/core": "^2.15.2",
      },
  },
    "@parcel/types@^2.15.2": {
      dependencies: {
        "@parcel/core": "^2.15.2",
      },
  },
  "react-resizable@^3.0.5": {
      peerDependencies: {
        "react-dom": ">=16.3.0",
      },
  },
}