nodeLinker: node-modules

packageExtensions: {
<<<<<<< HEAD
  "@parcel/node-resolver-core@^3.6.2": {
      dependencies: {
        "@parcel/core": "^2.15.2",
      },
  },
    "@parcel/types@^2.15.2": {
      dependencies: {
        "@parcel/core": "^2.15.2",
      },
  },
  "react-resizable@^3.0.5": {
      peerDependencies: {
        "react-dom": ">=16.3.0",
=======
  "@parcel/node-resolver-core@^3.3.0": {
      dependencies: {
        "@parcel/core": "*",
      },
  },
    "@parcel/resolver-default@^2.12.0": {
      dependencies: {
        "@parcel/core": "*",
      },
  },
    "@parcel/types@^2.12.0": {
      dependencies: {
        "@parcel/core": "*",
>>>>>>> a6c87f08208df72c62a770656b646a60cc9b7ed7
      },
  },
}