nodeLinker: node-modules

packageExtensions: {
  "@parcel/node-resolver-core@^3.3.0": {
      dependencies: {
        "@parcel/core": "*",
      },
  },
    "@parcel/resolver-default@^2.12.0": {
      dependencies: {
        "@parcel/core": "*",
      },
  },
    "@parcel/types@^2.12.0": {
      dependencies: {
        "@parcel/core": "*",
      },
  },
}