import { precacheAndRoute, createHandlerBoundToURL  } from "workbox-precaching"
import { registerRoute } from 'workbox-routing';
import { PDAgifs, FSAgifs, TMgifs } from './config/tour-gifs-manifest.json'

self.addEventListener("install", (event) => {
  console.log("[SW] Install event");
  // Activate this worker immediately, skipping waiting
  self.skipWaiting();

  event.waitUntil(
    (async () => {
      // Once install completes, tell clients that offline is ready
      const clientsList = await self.clients.matchAll({ includeUncontrolled: true });
      for (const client of clientsList) {
        client.postMessage({ type: "OFFLINE_READY" });
      }
    })()
  );
});

// Listen for activate event
self.addEventListener("activate", () => {
  console.log("[SW] Activate event");
  // Take control of all clients (pages) immediately
  clients.claim();
});

const manifest = self.__WB_MANIFEST || [];

const formatCacheEntries = (links) => {
  return links.map(url => ({url, revision: null}));
}

const extraCacheEntries = formatCacheEntries([...FSAgifs, ...PDAgifs, ...TMgifs]);

// Precache all assets generated by Parcel
precacheAndRoute([...manifest, ...extraCacheEntries]);

// direct all navigations to index.html because SPA
const handler = createHandlerBoundToURL('/index.html');
registerRoute(
  ({ request }) => request.mode === 'navigate',
  handler
);