import { precacheAndRoute, createHandlerBoundToURL  } from "workbox-precaching"
import { registerRoute } from 'workbox-routing';

// Precache all assets generated by Parcel
precacheAndRoute(self.__WB_MANIFEST || []);

// For SPA routes, fall back to index.html
const handler = createHandlerBoundToURL('/index.html');
registerRoute(
  ({ request }) => request.mode === 'navigate',
  handler
);
