importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.5.4/workbox-sw.js');

const { precaching, routing, strategies } = workbox;
const { precacheAndRoute } = precaching;
const { registerRoute } = routing;
const { NetworkFirst, StaleWhileRevalidate } = strategies;

// Precache all assets generated by Parcel
precacheAndRoute(self.__WB_MANIFEST || []);

registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'html-cache'
  })
)

registerRoute(
  ({ request }) => ['style', 'script', 'worker'].includes(request.destination),
  new StaleWhileRevalidate({
    cacheName: 'static-resources'
  })
)