name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: ./.github/actions/setup

    - name: Build project
      run: yarn build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./frontend/dist/
        clean-exclude: pr-preview/