name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: ./.github/actions/setup

    - name: Build project
      run: yarn build

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./frontend/dist/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
