name: Deploy PR previews
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: 
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set PR preview sub path env variable
        shell: bash
        run: echo 'SUB_PATH=/automatarium/pr-preview/pr-${{ github.event.number }}' >> frontend/.env

      - uses: ./.github/actions/setup

      - name: Build project
        if: github.event.action != 'closed'
        run: yarn build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.6.2
        with:
          source-dir: ./frontend/dist/