name: Deploy PR previews
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

env:
  PREVIEW-PR: pr-preview/pr-${{ github.ref }}

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup

      - name: Install Yarn Dependencies and build project
        if: github.event.action != 'closed'
        run: yarn build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.6.2
        with:
          source-dir: ./frontend/dist/