name: Upload dist folder
on:
  release:
    types:
      - published

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js Latest LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Enabling Corepack
        run: corepack enable

      - name: Installing Latest Yarn
        run: yarn set version stable && yarn install

      - name: Install Yarn Dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: 'automatarium_dist'
          path: ./frontend/dist/
