name: Send Latest Build
on:
  push:
    branches:
      - fix/send-email

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup

      - name: Build project
        run: yarn build

      - name: Zip dist folder to send
        run: cd frontend && zip -r automatarium_dist.zip ./dist/

      - name: Upload dist zip to GH Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'automatarium_dist'
          path: automatarium_dist.zip

      - name: Send email with latest build
        uses: cinotify/github-action@main
        with:
          to: 's3946986@student.rmit.edu.au'
          subject: 'Automatarium Latest Build'
          body: 'Hi Team, <br><br> A recent push has been made to the main branch.
                Please find the latest build of Automatarium attached. <br><br> 
                To view more about the changes, please see the commit details at
                https://github.com/automatarium/automatarium/commit/${{ github.sha }}. <br><br>
                Best Regards, <br> Automatarium CI System'
          type: 'text/html'
          attachment: 'automatarium_dist.zip'
