name: Setup dependencies
on:
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js Latest LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Enabling Corepack
        run: corepack enable

      - name: Installing Latest Yarn
        run: yarn set version stable && yarn install

      - name: Install Yarn Dependencies
        run: yarn